import { escapeHtml as h } from './utils.js';
import { state } from './state.js';
import { getDipStructure } from './dipStructure.js';
import { exampleData } from './messageExamplesData.js';
import { relevantChanges, changeReviewDate, releaseIndex } from './messageChanges.js';

const operationsSource = 'https://bscdocs.elexon.co.uk/data-integration-platform/dsd002-annex-2-detailed-dip-operational-requirements';
const sourceLink = (url,label) => `<a href="${h(url)}" target="_blank" rel="noopener">${h(label)} ↗</a>`;
function selection(iface, tab) {
  const structure = getDipStructure(iface,state.dataBlocksCatalogue,state.currentDipVariants[iface.id]);
  state.currentDipVariants[iface.id] = structure.event;
  return { structure, control: `<div class="event-select"><label for="guidanceEvent">Event variant</label><select id="guidanceEvent" data-action="dip-event" data-detail-tab="${tab}" data-id="${h(iface.id)}">${structure.eventCodes.map(e => `<option value="${h(e)}" ${e === structure.event ? 'selected' : ''}>${h(e)}</option>`).join('')}</select></div>` };
}
function inspectLink(iface,event,node) {
  const params = new URLSearchParams({view:'interfaces',selected:iface.id,tab:'message',event,block:node.path});
  return `<a class="example-block-link" href="?${h(params.toString())}"><code>${h(node.path)}</code><span>${h(node.schemaRef || node.key)} →</span></a>`;
}
function blockLinks(iface,event,nodes) {
  return nodes.map(n => (n.fields?.length ? inspectLink(iface,event,n) : '') + blockLinks(iface,event,n.children || [])).join('');
}
function jsonPanel(id,value,label) {
  return `<div class="example-code-toolbar"><strong>${h(label)}</strong><div><button class="utility-button" data-copy-example="${id}">Copy JSON</button><button class="utility-button" data-download-example="${id}">Download JSON</button></div></div><pre class="message-json" id="${id}" tabindex="0" aria-label="${h(label)}">${h(JSON.stringify(value,null,2))}</pre>`;
}
function issueList(issues,label) {
  return issues.length ? `<details class="example-issues"><summary>${h(label)} (${issues.length})</summary><ul>${issues.map(i => `<li><code>${h(i)}</code></li>`).join('')}</ul></details>` : '';
}
export function renderExamples(iface) {
  const {structure,control} = selection(iface,'examples');
  const id = iface.id.split('/')[0];
  const generated = exampleData.generated[id]?.[structure.event];
  const official = exampleData.published[id]?.[structure.event];
  if (!generated) return '<section class="section-card section-card-pad"><h2>Example unavailable</h2><p>No exact schema is available for this event.</p></section>';
  return `<section class="section-card"><div class="structure-topbar"><div><h2>Example messages</h2><p>Explore the JSON, then follow a block into its field definitions.</p></div>${control}</div>
    <div class="guidance-pad"><div class="guidance-notice"><strong>Generated illustration · Elexon ${h(exampleData.source.version)} schema</strong><p>All properties are shown, including optional ones, with sample values and short illustrative lists. This is a payload illustration, not a ready-to-send request or a business-valid message. Square brackets in event codes follow the published schema.</p></div>
    <div class="example-layout"><div>${jsonPanel('generated-example',generated.value,'Generated payload illustration')}${issueList(generated.issues,'Illustration constraints needing attention')}</div><aside class="example-index"><h3>Inspect a block</h3><p>Open the corresponding field definitions.</p>${blockLinks(iface,structure.event,[...structure.common,...structure.custom])}</aside></div>
    <div class="published-example"><h3>Elexon’s published example</h3>${official ? `<p>Preserved as supplied: <code>${h(official.name)}</code>. Differences from the current schema are listed below; this example is not a validated template.</p>${issueList(official.issues,'Differences detected against the current schema')}<details><summary>Show published JSON</summary>${jsonPanel('published-example',official.value,'Elexon published example')}</details>` : '<p>No published example for this event was found in the bundled Elexon specification. The illustration above is generated by DIPScope.</p>'}</div>
    <p class="guidance-source">${sourceLink(exampleData.source.url,'Elexon OpenAPI '+exampleData.source.version)} · Source snapshot checked ${h(exampleData.source.checkedDate)}. Comparison notes cover structure and basic field constraints, not full DIP validation.</p></div></section>`;
}

export function renderMessageJourney(iface, embedded = false) {
  const {structure,control} = selection(iface,embedded ? 'overview' : 'journey');
  const [incoming,outgoing] = iface.id.split('/');
  const roles = {
    S0:['Sender','Identifies the interface, event and schema version.'],
    S1:['Sender','Identifies the sender and its reference/timestamp.'],
    A0:['Sender + DIP','The sender supplies primary addressing when needed; DIP determines secondary and always recipients.'],
    D0:['DIP','Added for publication, including transaction and publication information.'],
    M0:['Sender','Identifies the MPAN and associated context.'],
    R0:['Message originator','Response information where this event includes it.'],
    R1:['Message originator','Response information; this schema uses R1 referencing R0.']
  };
  return `<section class="section-card"><div class="structure-topbar"><div><h2>From IF to PUB</h2><p>Understand the journey of ${h(incoming)} and its publication.</p></div>${control}</div><div class="guidance-pad">
    <ol class="message-journey"><li><span>1 · Submit</span><strong>${h(incoming)}</strong><p>The sender submits the message to DIP.</p></li><li><span>2 · Process</span><strong>DIP</strong><p>DIP checks and routes the message, adding its publication metadata.</p></li><li><span>3 · Deliver</span><strong>${h(outgoing || 'Publication')}</strong><p>The recipient receives the publication through its webhook.</p></li></ol>
    <p>IF and PUB describe the incoming and outgoing legs of the same exchange. A business response is a separate message exchange.</p>
    <div class="data-table-wrap"><table class="data-table"><thead><tr><th>Common block</th><th>Provided by</th><th>What to look for</th><th>Inspect</th></tr></thead><tbody>${structure.common.map(n => {const role = roles[n.key] || ['See message definition','Use the published definition for this block.'];return `<tr><td><code>${h(n.key)}</code></td><td>${h(role[0])}</td><td>${h(role[1])}</td><td>${inspectLink(iface,structure.event,n)}</td></tr>`;}).join('')}</tbody></table></div>
    <div class="guidance-notice"><strong>Reading a received publication</strong><p>CommonBlock is augmented by DIP. CustomBlock carries the business content; recipient-specific obfuscation can mask values. Missing and null are different—check the selected event’s field definitions.</p><p>D0’s optional presence in a shared schema does not mean the sender is responsible for supplying it.</p></div>
    <p class="guidance-source">General flow: ${sourceLink(operationsSource,'DSD002 Annex 2, sections 7 and 9')} · Listed blocks come from this event’s Elexon ${h(iface.technicalSource?.version || '')} schema. This explains block ownership, not a separate send/receive validation schema or a certification of catalogue routing.</p>
    </div></section>`;
}

export function renderMessageChanges(iface) {
  const records = relevantChanges(iface);
  const localNameChanges = (iface.catalogueEventCodes || []).filter(e => !iface.eventCodes.includes(e));
  return `<section class="section-card"><div class="structure-topbar"><div><h2>Changes affecting this message</h2><p>Selected Elexon records relevant to ${h(iface.id)} · reviewed ${changeReviewDate}</p></div></div><div class="guidance-pad"><div class="guidance-notice"><strong>A curated snapshot</strong><p>This is a selected set of reviewed changes, not a complete or live change register. A scheduled date is not confirmation of deployment.</p></div>
    <div class="change-list">${records.length ? records.map(c => `<article class="change-card"><div class="change-card-top"><code>${h(c.id)}</code><span class="structure-status status-partial">${h(c.status)}</span></div><h3>${h(c.title)}</h3><p>${h(c.summary)}</p><p><strong>Why it appears here:</strong> ${h(c.relevance)}</p><p><strong>${h(c.dateLabel)}:</strong> <time>${h(c.date)}</time></p><details><summary>Evidence and limits</summary><p>${h(c.evidence)}</p></details><p>${c.links.map(l => sourceLink(l.url,l.label)).join(' · ')}</p></article>`).join('') : '<p>No related change has been mapped in this snapshot. This does not mean there are no changes.</p>'}</div>
    <details class="local-change"><summary>DIPScope data update · ${h(iface.technicalSource?.checkedDate || '')}</summary><p>The technical tree was imported from Elexon ${h(iface.technicalSource?.version || '')}. This is a local reconciliation record, not an Elexon release announcement.</p>${localNameChanges.length ? `<p>Previous catalogue events absent from the source: ${h(localNameChanges.join(', '))}. Published events now include ${h(iface.eventCodes.join(', '))}.</p>` : ''}<p><a href="sources/reconciliation-report.json" target="_blank" rel="noopener">View reconciliation record</a></p></details>
    <p class="guidance-source">${sourceLink('https://www.elexon.co.uk/data-integration-platform/change-requests/','Browse Elexon change requests')} · ${sourceLink(releaseIndex,'Browse Elexon releases')}</p></div></section>`;
}
