import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {buildCandidate,runUpdate,discoverVersions,preflight,hash} from './update.mjs';
delete process.env.GITHUB_OUTPUT;
delete process.env.GITHUB_STEP_SUMMARY;
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const raw=fs.readFileSync(path.join(root,'sources/elexon-current.json'));
const spec=JSON.parse(raw);
const data=JSON.parse(fs.readFileSync(path.join(root,'interfaceData.json')));
const watch=JSON.parse(fs.readFileSync(path.join(root,'sources/elexon-upstream.json')));
const url=data._catalogueMeta.reconciliation.url;
assert.deepEqual(discoverVersions('api-spec-2.9.0-resolved.yaml api-spec-2.10.0-resolved.json api-spec-3.0.0-preview-resolved.yaml'),['2.9.0','2.10.0']);
function fixtureRoot(){
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'dipscope-test-'));
  for(const sub of ['sources','js'])fs.mkdirSync(path.join(dir,sub));
  for(const file of ['interfaceData.json','sources/elexon-current.json','sources/elexon-upstream.json','js/messageExamplesData.js'])fs.copyFileSync(path.join(root,file),path.join(dir,file));
  return dir;
}
const unchanged=fixtureRoot();
const original=hash(fs.readFileSync(path.join(unchanged,'interfaceData.json')));
assert.equal((await runUpdate({root:unchanged,fixture:{raw,url,watch}})).changed,false);
assert.equal(hash(fs.readFileSync(path.join(unchanged,'interfaceData.json'))),original);
const sentinel=structuredClone(data);
sentinel.interfaces[0].description='User maintained description: retain exactly.';
fs.writeFileSync(path.join(unchanged,'interfaceData.json'),JSON.stringify(sentinel));
const candidate=await buildCandidate(unchanged,raw,url,'2026-09-15');
assert.equal(candidate.after.interfaces[0].description,sentinel.interfaces[0].description);
const changedSpec=structuredClone(spec);
const key=Object.keys(changedSpec.components.schemas).find(k=>k.startsWith('DI-'));
assert.ok(key);
changedSpec.components.schemas[key].description='Updated official technical description for regression test.';
const changedRoot=fixtureRoot();
assert.equal((await runUpdate({root:changedRoot,fixture:{raw:JSON.stringify(changedSpec),url,watch}})).changed,true);
assert.equal(JSON.parse(fs.readFileSync(path.join(changedRoot,'sources/elexon-current.json'))).components.schemas[key].description,changedSpec.components.schemas[key].description);
const invalid=structuredClone(spec);
invalid.components.schemas['IF-999-Payload']={type:'object'};
assert.throws(()=>preflight(invalid,data),/Interface list changed/);
const invalidRoot=fixtureRoot();
await assert.rejects(runUpdate({root:invalidRoot,fixture:{raw:JSON.stringify(invalid),url,watch}}));
assert.equal(hash(fs.readFileSync(path.join(invalidRoot,'interfaceData.json'))),original);
const external=structuredClone(spec);
external.components.schemas['ExternalTest']={$ref:'https://example.com/spec.json'};
assert.throws(()=>preflight(external,data),/External references/);
const downgraded=structuredClone(spec);downgraded.info.version='0.0.0';
await assert.rejects(runUpdate({root:invalidRoot,fixture:{raw:JSON.stringify(downgraded),url,watch}}),/downgrade/);
const watchOnly=structuredClone(watch);watchOnly.files[Object.keys(watch.files)[0]]='test-new-sha';
const watchResult=await runUpdate({root:invalidRoot,fixture:{raw,url,watch:watchOnly}});
assert.equal(watchResult.githubChanged,true);assert.equal(watchResult.changed,false);
assert.equal(hash(fs.readFileSync(path.join(invalidRoot,'interfaceData.json'))),original);
console.log('PASS: discovery, full schema reconciliation, business content preservation, unchanged source, same-version updates, upstream-only changes, invalid references, interface changes and downgrades.');
